name: BuildImage
on:
  push: 
    branches: 
      - release

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2
      - name: login-dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.USERNAMEDOCKERHUB}}
          password: ${{secrets.BUILDIMAGEDOCKERHUB}}
      - name: qemu
        uses: docker/setup-qemu-action@v1
      - name: build-x
        uses: docker/setup-buildx-action@v1
      - name: build-push-image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{secrets.USERNAMEDOCKERHUB}}/serverexpressjobs:latest